package com.provana.payment.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.HexFormat;

@Component
public class RazorpaySignatureValidator {

    private static final Logger log = LoggerFactory.getLogger(RazorpaySignatureValidator.class);
    private static final String HMAC_SHA256_ALGORITHM = "HmacSHA256";

    /**
     * Verifies payment callback signature generated by Razorpay Checkout.
     * Expected signature: HMAC-SHA256(razorpay_order_id + "|" + razorpay_payment_id, key_secret)
     */
    public boolean verifyPaymentSignature(String razorpayOrderId, String razorpayPaymentId, String razorpaySignature, String secret) {
        if (razorpayOrderId == null || razorpayPaymentId == null || razorpaySignature == null || secret == null) {
            return false;
        }

        try {
            String payload = razorpayOrderId + "|" + razorpayPaymentId;
            String expectedSignature = calculateHmacSha256(payload, secret);
            return MessageDigest.isEqual(
                    expectedSignature.getBytes(StandardCharsets.UTF_8),
                    razorpaySignature.trim().getBytes(StandardCharsets.UTF_8)
            );
        } catch (Exception e) {
            log.error("Error verifying Razorpay payment signature: {}", e.getMessage());
            return false;
        }
    }

    /**
     * Verifies webhook signature sent by Razorpay in the X-Razorpay-Signature header.
     * Expected signature: HMAC-SHA256(raw_request_body, webhook_secret)
     */
    public boolean verifyWebhookSignature(String rawBody, String webhookSignature, String webhookSecret) {
        if (rawBody == null || webhookSignature == null || webhookSecret == null) {
            return false;
        }

        try {
            String expectedSignature = calculateHmacSha256(rawBody, webhookSecret);
            return MessageDigest.isEqual(
                    expectedSignature.getBytes(StandardCharsets.UTF_8),
                    webhookSignature.trim().getBytes(StandardCharsets.UTF_8)
            );
        } catch (Exception e) {
            log.error("Error verifying Razorpay webhook signature: {}", e.getMessage());
            return false;
        }
    }

    /**
     * Computes lowercase Hex-encoded HMAC-SHA256 hash.
     */
    public String calculateHmacSha256(String data, String secret) throws Exception {
        Mac mac = Mac.getInstance(HMAC_SHA256_ALGORITHM);
        SecretKeySpec secretKeySpec = new SecretKeySpec(secret.getBytes(StandardCharsets.UTF_8), HMAC_SHA256_ALGORITHM);
        mac.init(secretKeySpec);
        byte[] rawHmac = mac.doFinal(data.getBytes(StandardCharsets.UTF_8));
        return HexFormat.of().formatHex(rawHmac);
    }
}
