export type UserRole =
  | "ADMIN"
  | "MANAGER"
  | "PRODUCT_MANAGER"
  | "CONTENT_MANAGER"
  | "ORDER_MANAGER"
  | "CUSTOMER";

export type Permission =
  // Catalogue & Products
  | "CATALOGUE_READ"
  | "CATALOGUE_WRITE"
  | "CATALOGUE_CREATE"
  | "CATALOGUE_UPDATE"
  | "CATALOGUE_DELETE"
  | "CATALOGUE_PUBLISH"
  | "CATALOGUE_MEDIA_MANAGE"
  | "CATEGORY_READ"
  | "CATEGORY_CREATE"
  | "CATEGORY_UPDATE"
  | "CATEGORY_DELETE"
  | "SUBCATEGORY_READ"
  | "SUBCATEGORY_CREATE"
  | "SUBCATEGORY_UPDATE"
  | "SUBCATEGORY_DELETE"
  | "BRAND_READ"
  | "BRAND_CREATE"
  | "BRAND_UPDATE"
  | "BRAND_DELETE"
  | "PRODUCT_READ"
  | "PRODUCT_CREATE"
  | "PRODUCT_UPDATE"
  | "PRODUCT_DELETE"
  | "PRODUCT_PUBLISH"
  | "PRODUCT_VARIANT_READ"
  | "PRODUCT_VARIANT_CREATE"
  | "PRODUCT_VARIANT_UPDATE"
  | "PRODUCT_VARIANT_DELETE"
  | "SKU_READ"
  | "SKU_CREATE"
  | "SKU_UPDATE"
  | "SKU_DELETE"
  | "PRODUCT_MEDIA_READ"
  | "PRODUCT_MEDIA_CREATE"
  | "PRODUCT_MEDIA_UPDATE"
  | "PRODUCT_MEDIA_DELETE"
  | "PRODUCT_NUTRITION_READ"
  | "PRODUCT_NUTRITION_WRITE"
  | "PRODUCT_FAQ_READ"
  | "PRODUCT_FAQ_WRITE"
  // Inventory
  | "INVENTORY_READ"
  | "INVENTORY_WRITE"
  | "INVENTORY_ADJUST"
  | "INVENTORY_TRANSFER"
  | "INVENTORY_REPORT_READ"
  // Orders, Fulfilment & Payments
  | "ORDER_MANAGE"
  | "ORDER_READ"
  | "ORDER_CREATE"
  | "ORDER_UPDATE"
  | "ORDER_STATUS_UPDATE"
  | "ORDER_CANCEL"
  | "ORDER_FULFILL"
  | "ORDER_REPORT_READ"
  | "PAYMENT_READ"
  | "PAYMENT_VERIFY"
  | "PAYMENT_REFUND"
  | "SHIPMENT_READ"
  | "SHIPMENT_CREATE"
  | "SHIPMENT_UPDATE"
  | "SHIPMENT_TRACK"
  | "SHIPMENT_FULFILL"
  | "RETURN_READ"
  | "RETURN_APPROVE"
  | "RETURN_REJECT"
  | "RETURN_PROCESS"
  | "REFUND_READ"
  | "REFUND_CREATE"
  | "REFUND_APPROVE"
  | "REFUND_PROCESS"
  // Customers
  | "CUSTOMER_READ"
  | "CUSTOMER_UPDATE"
  | "CUSTOMER_SUPPORT"
  // Users & RBAC
  | "USER_MANAGE"
  | "USER_READ"
  | "USER_CREATE"
  | "USER_UPDATE"
  | "USER_DELETE"
  | "ROLE_READ"
  | "ROLE_CREATE"
  | "ROLE_UPDATE"
  | "ROLE_DELETE"
  | "PERMISSION_READ"
  | "PERMISSION_ASSIGN"
  | "PERMISSION_REVOKE"
  | "RBAC_MANAGE"
  // CMS & Media
  | "CMS_READ"
  | "CMS_CREATE"
  | "CMS_UPDATE"
  | "CMS_DELETE"
  | "CMS_REVIEW"
  | "CMS_APPROVE"
  | "CMS_PUBLISH"
  | "CMS_SCHEDULE"
  | "MEDIA_READ"
  | "MEDIA_UPLOAD"
  | "MEDIA_UPDATE"
  | "MEDIA_DELETE"
  // Marketing
  | "COUPON_READ"
  | "COUPON_CREATE"
  | "COUPON_UPDATE"
  | "COUPON_DELETE"
  | "DISCOUNT_READ"
  | "DISCOUNT_CREATE"
  | "DISCOUNT_UPDATE"
  | "DISCOUNT_DELETE"
  | "CAMPAIGN_READ"
  | "CAMPAIGN_CREATE"
  | "CAMPAIGN_UPDATE"
  | "CAMPAIGN_DELETE"
  | "CAMPAIGN_PUBLISH"
  // Reviews
  | "REVIEW_READ"
  | "REVIEW_CREATE"
  | "REVIEW_MODERATE"
  | "REVIEW_APPROVE"
  | "REVIEW_REJECT"
  | "REVIEW_DELETE"
  // Reports & Analytics
  | "REPORT_READ"
  | "REPORT_EXPORT"
  | "REPORT_OPERATIONAL_READ"
  | "REPORT_CATALOGUE_READ"
  | "REPORT_ORDER_READ"
  | "REPORT_CONTENT_READ"
  | "ANALYTICS_READ"
  | "ANALYTICS_EXPORT"
  // AI
  | "AI_ASSISTANT_USE"
  | "AI_PRODUCT_RECOMMENDATION"
  | "AI_CATALOGUE_INSIGHTS"
  | "AI_ORDER_INSIGHTS"
  | "AI_CONTENT_GENERATE"
  | "AI_ADMIN_INSIGHTS"
  // System Settings & Audit
  | "SYSTEM_SETTINGS_READ"
  | "SYSTEM_SETTINGS_UPDATE"
  | "AUDIT_LOG_READ";

const ALL_PERMISSIONS: Permission[] = [
  "CATALOGUE_READ",
  "CATALOGUE_WRITE",
  "CATALOGUE_CREATE",
  "CATALOGUE_UPDATE",
  "CATALOGUE_DELETE",
  "CATALOGUE_PUBLISH",
  "CATALOGUE_MEDIA_MANAGE",
  "CATEGORY_READ",
  "CATEGORY_CREATE",
  "CATEGORY_UPDATE",
  "CATEGORY_DELETE",
  "SUBCATEGORY_READ",
  "SUBCATEGORY_CREATE",
  "SUBCATEGORY_UPDATE",
  "SUBCATEGORY_DELETE",
  "BRAND_READ",
  "BRAND_CREATE",
  "BRAND_UPDATE",
  "BRAND_DELETE",
  "PRODUCT_READ",
  "PRODUCT_CREATE",
  "PRODUCT_UPDATE",
  "PRODUCT_DELETE",
  "PRODUCT_PUBLISH",
  "PRODUCT_VARIANT_READ",
  "PRODUCT_VARIANT_CREATE",
  "PRODUCT_VARIANT_UPDATE",
  "PRODUCT_VARIANT_DELETE",
  "SKU_READ",
  "SKU_CREATE",
  "SKU_UPDATE",
  "SKU_DELETE",
  "PRODUCT_MEDIA_READ",
  "PRODUCT_MEDIA_CREATE",
  "PRODUCT_MEDIA_UPDATE",
  "PRODUCT_MEDIA_DELETE",
  "PRODUCT_NUTRITION_READ",
  "PRODUCT_NUTRITION_WRITE",
  "PRODUCT_FAQ_READ",
  "PRODUCT_FAQ_WRITE",
  "INVENTORY_READ",
  "INVENTORY_WRITE",
  "INVENTORY_ADJUST",
  "INVENTORY_TRANSFER",
  "INVENTORY_REPORT_READ",
  "ORDER_MANAGE",
  "ORDER_READ",
  "ORDER_CREATE",
  "ORDER_UPDATE",
  "ORDER_STATUS_UPDATE",
  "ORDER_CANCEL",
  "ORDER_FULFILL",
  "ORDER_REPORT_READ",
  "PAYMENT_READ",
  "PAYMENT_VERIFY",
  "PAYMENT_REFUND",
  "SHIPMENT_READ",
  "SHIPMENT_CREATE",
  "SHIPMENT_UPDATE",
  "SHIPMENT_TRACK",
  "SHIPMENT_FULFILL",
  "RETURN_READ",
  "RETURN_APPROVE",
  "RETURN_REJECT",
  "RETURN_PROCESS",
  "REFUND_READ",
  "REFUND_CREATE",
  "REFUND_APPROVE",
  "REFUND_PROCESS",
  "CUSTOMER_READ",
  "CUSTOMER_UPDATE",
  "CUSTOMER_SUPPORT",
  "USER_MANAGE",
  "USER_READ",
  "USER_CREATE",
  "USER_UPDATE",
  "USER_DELETE",
  "ROLE_READ",
  "ROLE_CREATE",
  "ROLE_UPDATE",
  "ROLE_DELETE",
  "PERMISSION_READ",
  "PERMISSION_ASSIGN",
  "PERMISSION_REVOKE",
  "RBAC_MANAGE",
  "CMS_READ",
  "CMS_CREATE",
  "CMS_UPDATE",
  "CMS_DELETE",
  "CMS_REVIEW",
  "CMS_APPROVE",
  "CMS_PUBLISH",
  "CMS_SCHEDULE",
  "MEDIA_READ",
  "MEDIA_UPLOAD",
  "MEDIA_UPDATE",
  "MEDIA_DELETE",
  "COUPON_READ",
  "COUPON_CREATE",
  "COUPON_UPDATE",
  "COUPON_DELETE",
  "DISCOUNT_READ",
  "DISCOUNT_CREATE",
  "DISCOUNT_UPDATE",
  "DISCOUNT_DELETE",
  "CAMPAIGN_READ",
  "CAMPAIGN_CREATE",
  "CAMPAIGN_UPDATE",
  "CAMPAIGN_DELETE",
  "CAMPAIGN_PUBLISH",
  "REVIEW_READ",
  "REVIEW_CREATE",
  "REVIEW_MODERATE",
  "REVIEW_APPROVE",
  "REVIEW_REJECT",
  "REVIEW_DELETE",
  "REPORT_READ",
  "REPORT_EXPORT",
  "REPORT_OPERATIONAL_READ",
  "REPORT_CATALOGUE_READ",
  "REPORT_ORDER_READ",
  "REPORT_CONTENT_READ",
  "ANALYTICS_READ",
  "ANALYTICS_EXPORT",
  "AI_ASSISTANT_USE",
  "AI_PRODUCT_RECOMMENDATION",
  "AI_CATALOGUE_INSIGHTS",
  "AI_ORDER_INSIGHTS",
  "AI_CONTENT_GENERATE",
  "AI_ADMIN_INSIGHTS",
  "SYSTEM_SETTINGS_READ",
  "SYSTEM_SETTINGS_UPDATE",
  "AUDIT_LOG_READ",
];

export const ROLE_PERMISSIONS: Record<UserRole, Set<Permission>> = {
  ADMIN: new Set(ALL_PERMISSIONS),

  PRODUCT_MANAGER: new Set([
    "CATALOGUE_READ",
    "CATALOGUE_WRITE",
    "CATALOGUE_CREATE",
    "CATALOGUE_UPDATE",
    "CATALOGUE_DELETE",
    "CATALOGUE_PUBLISH",
    "CATALOGUE_MEDIA_MANAGE",
    "CATEGORY_READ",
    "CATEGORY_CREATE",
    "CATEGORY_UPDATE",
    "CATEGORY_DELETE",
    "SUBCATEGORY_READ",
    "SUBCATEGORY_CREATE",
    "SUBCATEGORY_UPDATE",
    "SUBCATEGORY_DELETE",
    "BRAND_READ",
    "BRAND_CREATE",
    "BRAND_UPDATE",
    "BRAND_DELETE",
    "PRODUCT_READ",
    "PRODUCT_CREATE",
    "PRODUCT_UPDATE",
    "PRODUCT_DELETE",
    "PRODUCT_PUBLISH",
    "PRODUCT_VARIANT_READ",
    "PRODUCT_VARIANT_CREATE",
    "PRODUCT_VARIANT_UPDATE",
    "PRODUCT_VARIANT_DELETE",
    "SKU_READ",
    "SKU_CREATE",
    "SKU_UPDATE",
    "SKU_DELETE",
    "PRODUCT_MEDIA_READ",
    "PRODUCT_MEDIA_CREATE",
    "PRODUCT_MEDIA_UPDATE",
    "PRODUCT_MEDIA_DELETE",
    "PRODUCT_NUTRITION_READ",
    "PRODUCT_NUTRITION_WRITE",
    "PRODUCT_FAQ_READ",
    "PRODUCT_FAQ_WRITE",
    "REPORT_CATALOGUE_READ",
    "AI_PRODUCT_RECOMMENDATION",
    "AI_CATALOGUE_INSIGHTS",
  ]),

  MANAGER: new Set([
    "CATALOGUE_READ",
    "INVENTORY_READ",
    "INVENTORY_WRITE",
    "INVENTORY_ADJUST",
    "INVENTORY_TRANSFER",
    "INVENTORY_REPORT_READ",
    "ORDER_MANAGE",
    "ORDER_READ",
    "ORDER_UPDATE",
    "ORDER_STATUS_UPDATE",
    "ORDER_CANCEL",
    "ORDER_FULFILL",
    "ORDER_REPORT_READ",
    "PAYMENT_READ",
    "SHIPMENT_READ",
    "SHIPMENT_CREATE",
    "SHIPMENT_UPDATE",
    "SHIPMENT_TRACK",
    "SHIPMENT_FULFILL",
    "RETURN_READ",
    "RETURN_APPROVE",
    "RETURN_REJECT",
    "RETURN_PROCESS",
    "REFUND_READ",
    "REFUND_CREATE",
    "REFUND_PROCESS",
    "CUSTOMER_READ",
    "CUSTOMER_SUPPORT",
    "REPORT_OPERATIONAL_READ",
    "REPORT_ORDER_READ",
    "AI_ORDER_INSIGHTS",
  ]),

  CONTENT_MANAGER: new Set([
    "CMS_READ",
    "CMS_CREATE",
    "CMS_UPDATE",
    "CMS_DELETE",
    "CMS_REVIEW",
    "CMS_APPROVE",
    "CMS_PUBLISH",
    "CMS_SCHEDULE",
    "MEDIA_READ",
    "MEDIA_UPLOAD",
    "MEDIA_UPDATE",
    "MEDIA_DELETE",
    "REPORT_CONTENT_READ",
    "AI_CONTENT_GENERATE",
  ]),

  ORDER_MANAGER: new Set([
    "ORDER_MANAGE",
    "ORDER_READ",
    "ORDER_UPDATE",
    "ORDER_STATUS_UPDATE",
    "ORDER_CANCEL",
    "ORDER_FULFILL",
    "ORDER_REPORT_READ",
    "PAYMENT_READ",
    "SHIPMENT_READ",
    "SHIPMENT_CREATE",
    "SHIPMENT_UPDATE",
    "SHIPMENT_TRACK",
    "SHIPMENT_FULFILL",
    "RETURN_READ",
    "RETURN_APPROVE",
    "RETURN_REJECT",
    "RETURN_PROCESS",
    "REFUND_READ",
    "REFUND_CREATE",
    "CUSTOMER_READ",
    "CUSTOMER_SUPPORT",
    "REPORT_ORDER_READ",
    "AI_ORDER_INSIGHTS",
  ]),

  CUSTOMER: new Set([
    "CATALOGUE_READ",
    "CATEGORY_READ",
    "SUBCATEGORY_READ",
    "BRAND_READ",
    "PRODUCT_READ",
    "PRODUCT_VARIANT_READ",
    "SKU_READ",
    "PRODUCT_MEDIA_READ",
    "PRODUCT_NUTRITION_READ",
    "PRODUCT_FAQ_READ",
    "ORDER_CREATE",
    "ORDER_READ",
    "REVIEW_READ",
    "REVIEW_CREATE",
    "AI_ASSISTANT_USE",
    "AI_PRODUCT_RECOMMENDATION",
  ]),
};

/**
 * Check if a given role has a specific permission.
 */
export function hasPermission(role: UserRole | undefined | null, permission: Permission): boolean {
  if (!role) return false;
  const perms = ROLE_PERMISSIONS[role];
  return perms ? perms.has(permission) : false;
}

/**
 * Check if a user or role has any of the specified permissions.
 */
export function hasAnyPermission(role: UserRole | undefined | null, permissions: Permission[]): boolean {
  if (!role) return false;
  const perms = ROLE_PERMISSIONS[role];
  if (!perms) return false;
  return permissions.some((p) => perms.has(p));
}

/**
 * Check if a user or role has all of the specified permissions.
 */
export function hasAllPermissions(role: UserRole | undefined | null, permissions: Permission[]): boolean {
  if (!role) return false;
  const perms = ROLE_PERMISSIONS[role];
  if (!perms) return false;
  return permissions.every((p) => perms.has(p));
}

/**
 * Convenience helper for React components.
 * Usage: `can(user?.role, "PRODUCT_CREATE")`
 */
export const can = hasPermission;
